import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header1 from "@/components/header1";
import Footer from "@/components/footer";
import Header2 from "@/components/header2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header1 />
        <Header2/>
        {children}</body>
      <Footer/>
    </html>
  );
}